apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfi-history
  namespace: nfi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfi-models
  namespace: nfi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
