apiVersion: v1
kind: Service
metadata:
  name: nfi-api
  namespace: nfi
  labels:
    app.kubernetes.io/name: network-fault-intelligence-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: network-fault-intelligence-platform
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
